/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-10-18 02:03:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/member/../common/menubar.jsp", Long.valueOf(1665975780090L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\" />\r\n");
      out.write("        <title>Insert title here</title>\r\n");
      out.write("        <style>\r\n");
      out.write("            .outer {\r\n");
      out.write("                background-color: black;\r\n");
      out.write("                color: white;\r\n");
      out.write("                width: 1000px;\r\n");
      out.write("                margin: auto;\r\n");
      out.write("                margin-top: 50px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            #mypage-form>table {\r\n");
      out.write("                margin: auto;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            #mypage-form input {\r\n");
      out.write("                margin: 5px;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        ");
      out.write('\r');
      out.write('\n');

	// 로그인한 사용자의 정보를 session 에 담았기 때문에
	// 이 웹 애플리케이션의 어디서든지 해당 키값을 제시해서 로그인한 사용자의 정보를 꺼내올 수 있음
	Member loginUser = (Member)session.getAttribute("loginUser");
	// System.out.println(loginUser);
	// 로그인 전 menubar.jsp 로딩 시 : null
	// 로그인 후 menubar.jsp 로딩 시 : 로그인한 회원의 정보가 담긴 Member 객체
	
	// System.out.println(request.getContextPath()); // /jsp
	String contextPath = request.getContextPath();
	
	// 성공시 알람 문구 또한 session 에 담았기 때문에
	// session 으로부터 뽑기
	String alertMsg = (String)session.getAttribute("alertMsg");
	// System.out.println(alertMsg);
	// 로그인 성공 전 menubar.jsp 로딩 시 : null
	// 로그인 성공 후 menubar.jsp 로딩 시 : alert 로 띄워주고자 하는 문구 출력

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    #login-form, #user-info { float : right; }\r\n");
      out.write("\r\n");
      out.write("    #user-info a {\r\n");
      out.write("        text-decoration : none;\r\n");
      out.write("        color : black;\r\n");
      out.write("        font-size : 12px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-area { background-color : black; }\r\n");
      out.write("\r\n");
      out.write("    .menu {\r\n");
      out.write("        display : table-cell; /* 인라인 요소처럼 배치 가능 */\r\n");
      out.write("        height : 50px;\r\n");
      out.write("        width : 150px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a {\r\n");
      out.write("        text-decoration : none;\r\n");
      out.write("        color : white;\r\n");
      out.write("        font-size : 20px;\r\n");
      out.write("        font-weight : bold;\r\n");
      out.write("        display : block;\r\n");
      out.write("        width : 100%;\r\n");
      out.write("        height : 100%;\r\n");
      out.write("        line-height : 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a:hover {\r\n");
      out.write("        background-color : darkgray;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script> <!-- 온라인 방식 -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("		// script 태그 내에도 스크립틀릿과 같은 jsp 요소를 쓸 수 있다.\r\n");
      out.write("		var msg = \"");
      out.print( alertMsg );
      out.write("\"; // \"성공적으로 로그인이 되었습니다.\" / \"null\"\r\n");
      out.write("		\r\n");
      out.write("		if(msg != \"null\") {\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			// 알림창을 띄워준 후 session 에 담긴 해당 메세지를 지워줘야함\r\n");
      out.write("			// 안그러면 menubar.jsp 가 로딩될때마다 매번 alert 가 계속 뜰 것!!\r\n");
      out.write("			\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<h1 align=\"center\">Welcome D Class</h1>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"login-area\">\r\n");
      out.write("    \r\n");
      out.write("    	");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("	        <!-- 로그인 전에 보여지는 로그인 form -->\r\n");
      out.write("	        <!-- \r\n");
      out.write("	        	현재 나의 위치 : http://localhost:8888/jsp/\r\n");
      out.write("	        	로그인 버튼을 클릭했을 때 이동하고자 하는 위치 : http://localhost:8888/jsp/login.me\r\n");
      out.write("	        	\r\n");
      out.write("	        	절대경로 : /jsp/login.me\r\n");
      out.write("	        	상대경로 : login.me\r\n");
      out.write("	        -->\r\n");
      out.write("	        <form id=\"login-form\" action=\"");
      out.print( contextPath );
      out.write("/login.me\" method=\"post\">\r\n");
      out.write("	            <table>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>아이디 : </th>\r\n");
      out.write("	                    <td><input type=\"text\" name=\"userId\" required></td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>비밀번호 : </th>\r\n");
      out.write("	                    <td><input type=\"password\" name=\"userPwd\" required></td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th colspan=\"2\">\r\n");
      out.write("	                        <button type=\"submit\">로그인</button>\r\n");
      out.write("	                        <button type=\"button\" onclick=\"enrollPage();\">회원가입</button>\r\n");
      out.write("	                    </th>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	            </table>\r\n");
      out.write("	        </form>\r\n");
      out.write("	        <script>\r\n");
      out.write("	        	function enrollPage() {\r\n");
      out.write("	        		\r\n");
      out.write("	        		// location.href = \"/jsp/views/member/memberEnrollForm.jsp\";\r\n");
      out.write("	        		// 웹 애플리케이션의 디렉토리 구조가 url 에 노출되면 보안에 취약\r\n");
      out.write("	        		\r\n");
      out.write("	        		// 단순한 페이지 요청이라고 하더라도 반드시 Servlet 을 거쳐갈것!!\r\n");
      out.write("	        		location.href = \"");
      out.print( contextPath );
      out.write("/enrollForm.me\";\r\n");
      out.write("	        	}\r\n");
      out.write("	        </script>\r\n");
      out.write("	        \r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("	        <!-- 로그인 성공 후에 보여지는 프로필 화면 -->\r\n");
      out.write("	        <div id=\"user-info\">\r\n");
      out.write("	            <b>");
      out.print( loginUser.getUserName() );
      out.write("님</b> 환영합니다^^ <br><br>\r\n");
      out.write("	            <div align=\"center\">\r\n");
      out.write("	                <a href=\"");
      out.print( contextPath );
      out.write("/myPage.me\">마이페이지</a>\r\n");
      out.write("	                <a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <br clear=\"both\"> <!-- float 속성 해제 -->\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"nav-area\" align=\"center\">\r\n");
      out.write("        <!-- (div.menu>a)*4 + Enter -->\r\n");
      out.write("        <div class=\"menu\"><a href=\"\">HOME</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"\">공지사항</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"\">일반게시판</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"\">사진게시판</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            ");
 // 현재 로그인한 사용자의 정보를 자바 변수로 담기 //=> 아이디, 이름, 휴대폰, 이메일, 주소 관심분야
                String userId = loginUser.getUserId(); String userName = loginUser.getUserName();
                // String phone = loginUser.getPhone();
                // "010-1111-2222" / null => ""
                String phone = (loginUser.getPhone() == null) ? "" : loginUser.getPhone();
                // 삼항연산자
                String email =(loginUser.getEmail() == null) ? "" : loginUser.getEmail();
                String address = (loginUser.getAddress() == null) ? "" : loginUser.getAddress();
                String interest = (loginUser.getInterest() == null) ? "" : loginUser.getInterest();
                // "운동, 등산" 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"outer\">\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <h2 align=\"center\">마이페이지</h2>\r\n");
      out.write("\r\n");
      out.write("                    <!-- \r\n");
      out.write("			현재 나의 주소 : http://localhost:8888/jsp/myPage.me\r\n");
      out.write("			내가 요청을 보내고자 하는 주소 : http://localhost:8888/jsp/update.me\r\n");
      out.write("			\r\n");
      out.write("			절대경로 : /jsp/update.me\r\n");
      out.write("			상대경로 : update.me\r\n");
      out.write("		-->\r\n");
      out.write("                    <form id=\"mypage-form\" action=\"");
      out.print( contextPath );
      out.write("/update.me\" method=\"post\">\r\n");
      out.write("                        <!-- 아이디, 비밀번호, (비밀번호확인), 전화번호, 이메일, 주소, 취미 -->\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <!-- (tr>td*3)*8 + Enter -->\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>* 아이디</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input type=\"text\" name=\"userId\" maxlength=\"12\" required value=\"");
      out.print( userId );
      out.write("\"\r\n");
      out.write("                                        readonly />\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <!-- 아이디의 수정을 막기 위해 readonly 속성을 부여 -->\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>* 이름</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input type=\"text\" name=\"userName\" maxlength=\"6\" required value=\"");
      out.print( userName );
      out.write("\" />\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>&nbsp;&nbsp;전화번호</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input type=\"text\" name=\"phone\" placeholder=\"- 포함해서 입력\" value=\"");
      out.print( phone );
      out.write("\" />\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>&nbsp;&nbsp;이메일</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input type=\"email\" name=\"email\" value=\"");
      out.print( email );
      out.write("\" />\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>&nbsp;&nbsp;주소</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <input type=\"text\" name=\"address\" value=\"");
      out.print( address );
      out.write("\" />\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>&nbsp;&nbsp;관심분야</td>\r\n");
      out.write("                                <td colspan=\"2\">\r\n");
      out.write("                                    <!-- (input[type=checkbox name=interest id= value=]+label)*6 + Enter -->\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"interest\" id=\"sports\" value=\"운동\" />\r\n");
      out.write("                                    <label for=\"sports\">운동</label>\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"interest\" id=\"hiking\" value=\"등산\" />\r\n");
      out.write("                                    <label for=\"hiking\">등산</label>\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"interest\" id=\"fishing\" value=\"낚시\" />\r\n");
      out.write("                                    <label for=\"fishing\">낚시</label>\r\n");
      out.write("                                    <br />\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"interest\" id=\"cooking\" value=\"요리\" />\r\n");
      out.write("                                    <label for=\"cooking\">요리</label>\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"interest\" id=\"game\" value=\"게임\" />\r\n");
      out.write("                                    <label for=\"game\">게임</label>\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"interest\" id=\"movie\" value=\"영화\" />\r\n");
      out.write("                                    <label for=\"movie\">영화</label>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("\r\n");
      out.write("                        <script>\r\n");
      out.write("                            $(function () {\r\n");
      out.write("                                var interest = '");
      out.print( interest );
      out.write("'; // \"\" / \"운동, 등산\"\r\n");
      out.write("\r\n");
      out.write("                                // [input, input, .., input]\r\n");
      out.write("                                $('input[type=checkbox]').each(function () {\r\n");
      out.write("                                    // 순차적으로 접근한 input 요소의 value 속성값이\r\n");
      out.write("                                    // interest 라는 변수에 포함되었을 경우\r\n");
      out.write("                                    // => 해당 input 요소에 checked 속성 부여\r\n");
      out.write("                                    if (interest.search($(this).val()) != -1) {\r\n");
      out.write("                                        // 포함됬다면\r\n");
      out.write("                                        // interest 라는 문자열로부터 현재 체크박스의 value 속성이\r\n");
      out.write("                                        // 포함되지 않으면 -1 을 반환\r\n");
      out.write("\r\n");
      out.write("                                        // 해당 요소에 checked 속성 부여\r\n");
      out.write("                                        $(this).attr('checked', true);\r\n");
      out.write("                                    }\r\n");
      out.write("                                });\r\n");
      out.write("                            });\r\n");
      out.write("                        </script>\r\n");
      out.write("\r\n");
      out.write("                        <br /><br />\r\n");
      out.write("\r\n");
      out.write("                        <div align=\"center\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-secondary btn-sm\">\r\n");
      out.write("                                정보변경\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-warning btn-sm\" data-toggle=\"modal\"\r\n");
      out.write("                                data-target=\"#updatePwdForm\">\r\n");
      out.write("                                비밀번호변경\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger btn-sm\" data-toggle=\"modal\"\r\n");
      out.write("                                data-target=\"#deleteForm\">\r\n");
      out.write("                                회원탈퇴\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <br /><br />\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 회원탈퇴용 모달창 -->\r\n");
      out.write("                <!-- The Modal -->\r\n");
      out.write("                <div class=\"modal\" id=\"deleteForm\">\r\n");
      out.write("                    <div class=\"modal-dialog\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("                            <!-- Modal Header -->\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <h4 class=\"modal-title\">회원탈퇴</h4>\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("                                    &times;\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Modal body -->\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("                                <b>탈퇴 후 복구가 불가능합니다. <br />\r\n");
      out.write("                                    정말도 탈퇴하시겠습니까? <br /><br /></b>\r\n");
      out.write("                                <!--  현재 나의 위치 : http://localhost:8888/jsp/myPage.me\r\n");
      out.write("						  회원 탈퇴 요청 시 요청을 보내고자 하는 url 위치 : http://localhost:8888/jsp/delete.me\r\n");
      out.write("						  \r\n");
      out.write("						  절대경로 : /jsp/delete.me\r\n");
      out.write("						  상대경로 : delete.me\r\n");
      out.write("					 -->\r\n");
      out.write("                                <form action=\"");
      out.print(contextPath);
      out.write("/delete.me\" method=\"post\">\r\n");
      out.write("                                    <table>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>비밀번호</td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <input type=\"password\" name=\"userPwd\" required />\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    <br />\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-danger btn-sm\">\r\n");
      out.write("                                        탈퇴하기\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 비밀번호 변경용 모달창 -->\r\n");
      out.write("                <!-- The Modal -->\r\n");
      out.write("                <div class=\"modal\" id=\"updatePwdForm\">\r\n");
      out.write("                    <div class=\"modal-dialog\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("                            <!-- Modal Header -->\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <h4 class=\"modal-title\">비밀번호 변경</h4>\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("                                    &times;\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Modal body -->\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("                                <!--\r\n");
      out.write("                현재 나의 위치 : localhost:8888/jsp/myPage.me\r\n");
      out.write("                비밀번호 변경 요청 시 url : localhost:8888/jsp/updatePwd.me\r\n");
      out.write("\r\n");
      out.write("                절대경로 : /jsp/updatePwd.me\r\n");
      out.write("                상대경로 : updatePwd.me\r\n");
      out.write("            -->\r\n");
      out.write("                                <form action=\"");
      out.print( contextPath );
      out.write("/updatePwd.me\" method=\"post\">\r\n");
      out.write("                                    <!-- 현재 비밀번호, 변경할 비밀번호, 변경할 비밀번호 확인(재입력) -->\r\n");
      out.write("                                    <!-- 해당 회원의 아이디값을 애초에 숨겨서 보내기 -->\r\n");
      out.write("                                    <input type=\"hidden\" name=\"userId\" value=\"");
      out.print( userId );
      out.write("\" />\r\n");
      out.write("                                    <table>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>현재 비밀번호</td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <input type=\"password\" name=\"userPwd\" required />\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>변경할 비밀번호</td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <input type=\"password\" name=\"updatePwd\" required />\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>변경할 비밀번호 재입력</td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <input type=\"password\" name=\"checkPwd\" required />\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("\r\n");
      out.write("                                    <br />\r\n");
      out.write("\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-secondary btn-sm\"\r\n");
      out.write("                                        onclick=\"return validatePwd();\">\r\n");
      out.write("                                        비밀번호 변경\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("\r\n");
      out.write("                                <script>\r\n");
      out.write("                                    function validatePwd() {\r\n");
      out.write("                                        if (\r\n");
      out.write("                                            $('input[name=updatePwd]').val() !=\r\n");
      out.write("                                            $('input[name=checkPwd]').val()\r\n");
      out.write("                                        ) {\r\n");
      out.write("                                            alert('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("                                            return false;\r\n");
      out.write("                                        }\r\n");
      out.write("                                    }\r\n");
      out.write("                                </script>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
